# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'proto.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bproto.proto\"1\n\tPublicKey\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\t\n\x01\x65\x18\x02 \x01(\x03\x12\t\n\x01n\x18\x03 \x01(\x03\"\x1f\n\rClientRequest\x12\x0e\n\x06sender\x18\x01 \x01(\t\"<\n\x07Message\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x10\n\x08receiver\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\x0c\"\x1a\n\x08Response\x12\x0e\n\x06status\x18\x01 \x01(\t2\xc1\x01\n\x10MessagingService\x12*\n\x11RegisterPublicKey\x12\n.PublicKey\x1a\t.Response\x12.\n\x10RequestPublicKey\x12\x0e.ClientRequest\x1a\n.PublicKey\x12\"\n\x0bSendMessage\x12\x08.Message\x1a\t.Response\x12-\n\x0fReceiveMessages\x12\x0e.ClientRequest\x1a\x08.Message0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PUBLICKEY']._serialized_start=15
  _globals['_PUBLICKEY']._serialized_end=64
  _globals['_CLIENTREQUEST']._serialized_start=66
  _globals['_CLIENTREQUEST']._serialized_end=97
  _globals['_MESSAGE']._serialized_start=99
  _globals['_MESSAGE']._serialized_end=159
  _globals['_RESPONSE']._serialized_start=161
  _globals['_RESPONSE']._serialized_end=187
  _globals['_MESSAGINGSERVICE']._serialized_start=190
  _globals['_MESSAGINGSERVICE']._serialized_end=383
# @@protoc_insertion_point(module_scope)
