# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Messaging/message.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'Messaging/message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17Messaging/message.proto\"!\n\tPublicKey\x12\t\n\x01n\x18\x01 \x01(\x05\x12\t\n\x01\x65\x18\x02 \x01(\x05\"\x1f\n\x11UserIdentificator\x12\n\n\x02id\x18\x01 \x01(\t\"P\n\x13\x41\x64\x64PublicKeyRequest\x12 \n\x04user\x18\x01 \x01(\x0b\x32\x12.UserIdentificator\x12\x17\n\x03key\x18\x02 \x01(\x0b\x32\n.PublicKey\"<\n\x07Message\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x10\n\x08receptor\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"\x1a\n\x08Response\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\xbe\x01\n\x10MessagingService\x12/\n\x0c\x41\x64\x64PublicKey\x12\x14.AddPublicKeyRequest\x1a\t.Response\x12.\n\x0cGetPublicKey\x12\x12.UserIdentificator\x1a\n.PublicKey\x12\"\n\x0bSendMessage\x12\x08.Message\x1a\t.Response\x12%\n\x0fReceiveMessages\x12\x06.Empty\x1a\x08.Message0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Messaging.message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PUBLICKEY']._serialized_start=27
  _globals['_PUBLICKEY']._serialized_end=60
  _globals['_USERIDENTIFICATOR']._serialized_start=62
  _globals['_USERIDENTIFICATOR']._serialized_end=93
  _globals['_ADDPUBLICKEYREQUEST']._serialized_start=95
  _globals['_ADDPUBLICKEYREQUEST']._serialized_end=175
  _globals['_MESSAGE']._serialized_start=177
  _globals['_MESSAGE']._serialized_end=237
  _globals['_RESPONSE']._serialized_start=239
  _globals['_RESPONSE']._serialized_end=265
  _globals['_EMPTY']._serialized_start=267
  _globals['_EMPTY']._serialized_end=274
  _globals['_MESSAGINGSERVICE']._serialized_start=277
  _globals['_MESSAGINGSERVICE']._serialized_end=467
# @@protoc_insertion_point(module_scope)
